{
        "Bolum13.html#try-except-blokları Try-Except": {
                "Try-Except 1": "\ns1 = int(input('Birinci Sayı :'))\ns2 = int(input('İkinci Sayı :'))\ntry:\n\tsonuc = s1/s2\n\tprint('Sonuc :', sonuc)\nexcept ZeroDivisionError:\n\tprint('Bir sayıyı sıfıra bölemezsiniz lütfen sıfır dışında bir sayı girin')\n\n\n# Bir blok içerisinde hata olması durumunda,\n# Python except bloğuna atlar ve\n# oradaki kodların çalıştırılmasını sağlar.\n",
                "Try-Except 2": "\ntry:\n\ts1 = int(input('Birinci Sayı :'))\n\ts2 = int(input('İkinci Sayı :'))\n\tsonuc = s1/s2\n\tprint('Sonuc :', sonuc)\nexcept ZeroDivisionError:\n\tprint('Lütfen ikinci sayıya sıfırdan farklı bir değer girin…')\nexcept ValueError:\n\tprint('Lütfen sayısal bir karakter girin..')\nexcept:\n\tprint('Beklenmeyen bir hata oluştu')\n\n# Kullanıcı inputlara sıfırdan farklı sayılar girerse\n# program herhangi bir hata vermeyecek\n# ve sadece try bloğu çalışacaktır.\n\n# inputlardan herhangi birine sıfır veya farklı veri türünde değer\n# girilmesi durumunda except bloğu çalışıp bilgilendirme yapacaktır.\n\n# Except bloğuna hatanın türü yazılmadığında\n# yorumlayıcı tarafından bütün hataları kapsayacaktır.\n# Bunu da sadece except bloğu ile genel\n# olarak beklenmeyen bir hata oluştu, diye mesaj ile belirtilebilir.\n"
        },
        "Bolum13.html#try-except-as Try Except as": {
                "Try Except as 1": "\ntry:\n\ts1 = int(input('Birinci Sayı :'))\n\tsonuc = s1**2\n\tprint('Sonuc :', sonuc)\nexcept ValueError as hata:\n\tprint('Lütfen sayı giriniz')\n\tprint(hata)\n\n\n# Kullanıcıya Python’a ait hata mesajları\n# gösterilmek istendiğinde “as” ifadesi kullanılmaktadır.\n",
                "Try Except as 2": "\ntry:\n\ts1 = int(input('Birinci Sayı : '))\nexcept ValueError:\n\tprint('sayı girmediniz')\nelse:\n\ttry:\n\t\tprint(10/s1)\n\texcept ZeroDivisionError:\n\t\tprint('sayı sıfıra bölünemez')\n\n\n# Try except else, oluşabilecek hataları\n# adım adım ayıklanmak isteniyorsa\n# “else” ifadesi kullanılmaktadır.\n",
                "Try Except as 3": "\nwhile True:\n\ttry:\n\t\tx = input('Bir sayı girin: ')\n\t\tif not x:\n\t\t\tbreak\n\t\ty = 1/float(x)\n\texcept ValueError:\n\t\tprint('Geçersiz sayı')\n\t\tcontinue\n\texcept ZeroDivisionError:\n\t\tprint('Sıfıra bölme')\n\t\tcontinue\n\tprint(y)\n\n\n# Kullanıcı hata aldığında programın\n# devam etmesi için böyle bir uygulama yapılabilir.\n# Continue ifadesi ile sayı yanlış girilirse\n# tekrar girilmesi sağlanmaktadır."
        }
}